### ISSUE TITLE
If the batch size will influence the results. 

### ISSUE THREAD

**Issue by ShihuaHuang95** [jeromerony/fast_adversarial#2]
Thanks for such nice work! I am wondering if you have tested the different batch size will make a difference?

**Comment by jeromerony** [comment]
Mathematically speaking, it should not make any difference as the [ce_loss](https://github.com/jeromerony/fast_adversarial/blob/a15fbb33eff158ed3585a2933e0662aa12a49901/fast_adv/attacks/ddn.py#L98) is the sum of the loss for each element of the batch. I have not seen any difference when testing using the cudnn.deterministic flag.
