### ISSUE TITLE
how to limit the norm of the perturbation  of c&w and deepfool attack

### ISSUE THREAD

**Issue by xiahaifeng1995** [jeromerony/fast_adversarial#4]
Hi, how can I get the results of this column?
![image](https://user-images.githubusercontent.com/32216515/62849158-2dae4480-bd11-11e9-9822-69e211e363a3.png)

**Comment by jeromerony** [comment]
Hi, you can obtain this column by renorming the perturbation at 0.5 and testing the accuracy with the renormed perturbations.

**Comment by xiahaifeng1995** [comment]
So I just need to set a constraint after the perturbation  has been generated.

**Comment by jeromerony** [comment]
Well, there is no "constraint" on these attacks (neither on ours) but you can manually renorm the perturbation once it is generated. Assuming `delta` is the perturbation (not the perturbed image) added to the batch of images contained in [0, 1], you can renorm `delta` to the `target_norm` with:
```python
renormed_delta = torch.renorm(delta, 2, 0, target_norm)
```
Perturbations that have a smaller norm than `target_norm` will not be modified while the ones having larger norms will get renormed.

**Comment by xiahaifeng1995** [comment]
Thanks, it's useful.
